# Generated by Django 4.1.1 on 2022-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varauskalenteri', '0004_alter_tapahtuma_loppu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapahtuma',
            name='kuvaus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tapahtuma',
            name='loppu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
